### ISSUE TITLE
How to build locally?

### ISSUE THREAD

**Issue by yhyu13** [vectorch-ai/ScaleLLM#16]
Hi

I saw your promption here https://huggingface.co/TheBloke/Yi-34B-GPTQ/discussions/2#654b063883e7bfc43160ca0e

Maybe a stupid question, just wonder if this building is suffice for local deploy w/o docker (since my remote instance is already a docker instance, and I cannot create docker inside docker due to admin privilege not being granted), assumed all dep are resolved.

```
# build
RUN cmake -G Ninja -S . -B build
RUN cmake --build build --target all --config Release -j$(nproc)

# install
RUN cmake --install build --prefix /app
RUN pip3 install -r ./requirements.txt
```

**Comment by guocuimi** [comment]
Yeah it should be enough for binary. Let me know if you encounter any
problems.

**Comment by guocuimi** [comment]
Just a reminder, this project depends on huggingface safetensors. You need to install rust to get a success build. 

# install rust
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH=$HOME/.cargo/bin:$PATH
