### ISSUE TITLE
How to use a model that has been downloaded locally , Instead of downloading from huggingface when running container?

### ISSUE THREAD

**Issue by GitMiaoronghua** [vectorch-ai/ScaleLLM#19]

**Comment by guocuimi** [comment]
hello, thanks for using ScaleLLM.  please try following command and let me know if it works.

you can config it directly and pass it into ScaleLLM as gflags.
```
export MODEL_PATH=...
export MODEL_ID=...
docker run -it --gpus=all --net=host \
  -v $MODEL_PATH:$MODEL_PATH \
  -e DEVICE=cuda:0 \
  docker.io/vectorchai/scalellm:latest --logtostderr --model_path=$MODEL_PATH --model_id=$MODEL_ID
```

**Comment by GitMiaoronghua** [comment]
export MODEL_PATH=/raid/users/mrh/weights/dkmodels
export MODEL_ID=TheBlokeYi-34B-GPTQ
docker run -it --gpus=all --net=host \
  -v $MODEL_PATH:$MODEL_PATH \
  -e DEVICE=auto \
  docker.io/vectorchai/scalellm:latest --logtostderr --model_path=$MODEL_PATH --model_id=$MODEL_ID

result:
![image](https://github.com/vectorch-ai/ScaleLLM/assets/43289542/7b127954-e3e7-4517-8d7d-ec7ac79d833a)

**Comment by guocuimi** [comment]
oh, sorry to hear that you encounter the issue. could you try change the DEVICE to cuda:0,cuda:1,cuda:2,cuda:3 to help rule out potential problems. i havn't test it on 8 gpus yet, not sure if it is related.
```
export MODEL_PATH=/raid/users/mrh/weights/dkmodels
export MODEL_ID=TheBlokeYi-34B-GPTQ
docker run -it --gpus=all --net=host
-v $MODEL_PATH:$MODEL_PATH
-e DEVICE=cuda:0,cuda:1,cuda:2,cuda:3
docker.io/vectorchai/scalellm:latest --logtostderr --model_path=$MODEL_PATH --model_id=$MODEL_ID
```
