### ISSUE TITLE
pip install scalellm failure.

### ISSUE THREAD

**Issue by liutongxuan** [vectorch-ai/ScaleLLM#212]
### Reproduce the issue

pip install scalellm -i https://whl.vectorch.com/cu121/torch2.3/

### Install failure

Looking in indexes: https://whl.vectorch.com/cu121/torch2.3/
Collecting scalellm
  Downloading https://github.com/vectorch-ai/scalellm/releases/download/v0.1.1/scalellm-0.1.1%2Bcu121torch2.3-cp310-cp310-linux_x86_64.whl (78.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.2/78.2 MB 31.5 MB/s eta 0:00:00
Discarding https://github.com/vectorch-ai/scalellm/releases/download/v0.1.1/scalellm-0.1.1%2Bcu121torch2.3-cp310-cp310-linux_x86_64.whl#sha256=534f2032889356be51208215c3a55e79545ba218d3a826faa6f18ef3a587bd53 (from https://whl.vectorch.com/cu121/torch2.3/scalellm/): Requested scalellm from https://github.com/vectorch-ai/scalellm/releases/download/v0.1.1/scalellm-0.1.1%2Bcu121torch2.3-cp310-cp310-linux_x86_64.whl#sha256=534f2032889356be51208215c3a55e79545ba218d3a826faa6f18ef3a587bd53 has inconsistent version: expected '0.1.1+cu121torch2.3', but metadata has '0.1.1'
ERROR: Could not find a version that satisfies the requirement scalellm (from versions: 0.1.1+cu121torch2.3)
ERROR: No matching distribution found for scalellm

**Comment by guocuimi** [comment]
Thanks for reporting the issue. It should be fixed by the new commit above. let me test it in new release then close this issue.
