### ISSUE TITLE
Limit GPU Memory

### ISSUE THREAD

**Issue by Siegi96** [vectorch-ai/ScaleLLM#22]
Is it possible to limit GPU Memory used by ScaleLLM?

**Comment by guocuimi** [comment]
Thank you for using ScaleLLM. In ScaleLLM, GPU memory management can be controlled in two ways, with the system adhering to whichever limit is reached first. Here are the details:

Max Cache Size:

* Name: max_cache_size
Type: int64
Default Value: 5368709120 (which is approximately 5GB)
Description: This setting controls the maximum cache size in bytes. By default, it is set to 5GB.
Max Memory Utilization:

* Name: max_memory_utilization
Type: double
Default Value: 0.90 (90%)
Description: This setting determines the maximum memory utilization allowed. The default value is 0.9, meaning 90% utilization.

For example:
```
docker run -it --gpus=all --net=host --shm-size=1g \
  -v $HOME/.cache/huggingface/hub:/models \
  -e HF_MODEL_ID=01-ai/Yi-34B-Chat-4bits \
  -e DEVICE=auto \
  docker.io/vectorchai/scalellm:latest --logtostderr --model_type=Yi --max_cache_size=5000000000 --max_memory_utilization=0.80
```

BTW, you can retrieve a list of all supported gflags by using the following command: `curl localhost:9999/gflags`

**Comment by mskoric** [comment]
Hi @guocuimi ,

i've run into this "issue" and it seems that the limit isn't working correctly. The defauilt limit is 5GB and my GPU has 8 GB. It tries to allocate 11,32GB.  Here is some output.

`
scalellm-1               | I20240121 15:15:06.181690    13 engine.cpp:98] Initializing model with dtype: BFloat16
scalellm-1               | I20240121 15:15:06.186162    13 engine.cpp:107] Initializing model with ModelArgs: [model_type: llama, dtype: bfloat16, hidden_size: 4096, hidden_act: silu, intermediate_size: 11008, n_layers: 32, n_heads: 32, n_kv_heads: 4, vocab_size: 64000, rms_norm_eps: 1e-05, layer_norm_eps: 0, rotary_dim: 0, rope_theta: 5e+06, rope_scaling: 1, rotary_pct: 1, max_position_embeddings: 4096, bos_token_id: 1, eos_token_id: 2, use_parallel_residual: 0, attn_qkv_clip: 0, attn_qk_ln: 0, attn_alibi: 0, alibi_bias_max: 0, no_bias: 0, residual_post_layernorm: 0], QuantArgs: [quant_method: , bits: 0, group_size: 0, desc_act: 0, true_sequential: 0]
d02a6a1423d0_chatbot-ui  | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
scalellm-1               | I20240121 15:15:07.562232    13 model_loader.cpp:38] Loading model weights from /models/models--01-ai--Yi-6B/snapshots/76b645e036526955360d6b4e8a4b9ff1a1c04676/model-00001-of-00002.safetensors
scalellm-1               | I20240121 15:15:10.055896    13 model_loader.cpp:38] Loading model weights from /models/models--01-ai--Yi-6B/snapshots/76b645e036526955360d6b4e8a4b9ff1a1c04676/model-00002-of-00002.safetensors
scalellm-1               | I20240121 15:15:10.592322    13 engine.cpp:162] Initializing kv cache with block size: 16, max cache size: 5.00 GB, max memory utilization: 0.9
scalellm-1               | I20240121 15:15:10.592372    13 engine.cpp:179] Block size in bytes: 1.00 MB, block_size: 16, head_dim: 128, n_local_kv_heads: 4, n_layers: 32, dtype_size: 2
scalellm-1               | I20240121 15:15:10.592415    13 engine.cpp:198] cuda:0: allocated GPU memory: 11.32 GB, total GPU memory: 8.00 GB
scalellm-1               | F20240121 15:15:10.592442    13 engine.cpp:210] Check failed: max_cache_size > 0 (-4425172583 vs. 0) Not enough memory for the cache
scalellm-1               | *** Check failure stack trace: ***
scalellm-1               | *** Aborted at 1705850110 (unix time) try "date -d @1705850110" if you are using GNU date ***
scalellm-1               | PC: @                0x0 (unknown)
scalellm-1               | *** SIGABRT (@0xd) received by PID 13 (TID 0x7f2ccc887000) from PID 13; stack trace: ***
scalellm-1               |     @     0x7f2c5c7ee520 (unknown)
scalellm-1               |     @     0x7f2c5c8429fc pthread_kill
scalellm-1               |     @     0x7f2c5c7ee476 raise
scalellm-1               |     @     0x7f2c5c7d47f3 abort
scalellm-1               |     @     0x561ef174690d folly::(anonymous namespace)::wrapped_abort()
scalellm-1               |     @     0x561ef16fc509 google::LogMessage::Fail()
scalellm-1               |     @     0x561ef16fc44f google::LogMessage::SendToLog()
scalellm-1               |     @     0x561ef16fbc5f google::LogMessage::Flush()
scalellm-1               |     @     0x561ef16ffa3e google::LogMessageFatal::~LogMessageFatal()
scalellm-1               |     @     0x561ef169ddc5 llm::Engine::init_kv_cache()
scalellm-1               |     @     0x561ef169c77a llm::Engine::init()
scalellm-1               |     @     0x561ef15fe5e2 main
scalellm-1               |     @     0x7f2c5c7d5d90 (unknown)
scalellm-1               |     @     0x7f2c5c7d5e40 __libc_start_main
scalellm-1               |     @     0x561ef15fbd65 _start
scalellm-1               |     @                0x0 (unknown)
scalellm-1               | ./entrypoint.sh: line 28:    13 Aborted                 LD_LIBRARY_PATH=/app/lib:$LD_LIBRARY_PATH /app/bin/scalellm $ARGS "$@"

i use the docker-compose.yml with

`HF_MODEL_ID=01-ai/Yi-6B docker compose HF_MODEL_ID=01-ai/Yi-6B docker compose -f ./scalellm_compose.yml up`

`vectorchai/scalellm           latest    f264a19f4af5   6 weeks ago    4.04GB
vectorchai/scalellm-gateway   latest    a41cdb201a05   6 weeks ago    237MB
vectorchai/chatbot-ui         latest    0c28ac47ed68   2 months ago   1.3GB`


Should i open a new bug


Best Regards,

Majk



`

**Comment by guocuimi** [comment]
hello, I wanted to clarify that the max_cache_size parameter is specifically used to control the key-value (kv) cache size for inference, rather than managing the overall GPU memory usage. I observed that you are attempting to load the 01-yi 6b model, which has a size of approximately 11GB. Unfortunately, this model cannot be loaded on a GPU with only 8GB of memory.

To sum up, the GPU memory requirement is a combination of the memory needed for the model itself and the memory allocated for the kv cache.
Thanks
