### ISSUE TITLE
Can use this project without docker?

### ISSUE THREAD

**Issue by Arcmoon-Hu** [vectorch-ai/ScaleLLM#26]
Can I use this project in a python virtual env? Or must use docker?

**Comment by guocuimi** [comment]
Good question. For now, Scalellm only supports running in a docker. We will be trying to add python and nodejs wrapper once finishing ongoing performance optimizations. Stay tuned!

**Comment by guocuimi** [comment]
A quick update for you: python is supported in [latest release](https://github.com/vectorch-ai/ScaleLLM/releases/tag/v0.1.0). 
you can install scalellm with pip: `pip install scalellm` and start rest api server with `python3 -m scalellm.serve.api_server`
Please let me know if you have any questions. thanks
