### ISSUE TITLE
Deployment of glm-4-9b-chat model fails with SentencePiece tokenizer error

### ISSUE THREAD

**Issue by dengyingxu** [vectorch-ai/ScaleLLM#291]
Hello,

I am encountering an issue while trying to deploy the glm-4-9b-chat model using the scalellm repository. The deployment fails with an error related to the SentencePiece tokenizer. Below are the details of the error and the steps I have taken to troubleshoot it.

Error Message:

WARNING: Logging before InitGoogleLogging() is written to STDERR
I20240801 13:16:18.061883   140 llm_handler.cpp:171] Creating engine with devices: cuda:0
I20240801 13:16:18.070197   140 llm_engine.cpp:138] Initializing model from: /export/home/dengyingxu1/test_glm4_scalellm/models/glm-4-9b-chat
I20240801 13:16:18.070269   140 model_loader.cpp:184] Using SentencePiece tokenizer.
F20240801 13:16:18.083376   140 sentencepiece_tokenizer.cpp:36] Failed to load SentencePiece model from /export/home/dengyingxu1/test_glm4_scalellm/models/glm-4-9b-chat/tokenizer.model: Internal: /ScaleLLM/third_party/sentencepiece/sentencepiece_processor.cc(1102) [model_proto->ParseFromArray(serialized.data(), serialized.size())] , error Internal: /ScaleLLM/third_party/sentencepiece/sentencepiece_processor.cc(1102) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by guocuimi** [comment]
Thank you for reporting the issue. I've tested it on my end and encountered the same error with 'THUDM/glm-4-9b-chat'. I strongly suspect that the 'tokenizer.model' file is corrupted, as it fails to load even with the 'sentencepiece' package using the following code snippet:

```
pip install sentencepiece
>>> import sentencepiece as spm
>>> s = spm.SentencePieceProcessor(model_file='your_path_to/tokenizer.model')
```

I would recommend you report the issue to the model owner. let me know if something i can help.

**Comment by guocuimi** [comment]
oops, sounds glm-4-9b-chat is using 'tiktoken', let me take a further look.

**Comment by guocuimi** [comment]
just land a diff to support glm4 using 'tiktoken' tokenizer. https://github.com/vectorch-ai/ScaleLLM/pull/292

The issue should be fixed in next release.

**Comment by guocuimi** [comment]
[new release](https://pypi.org/project/scalellm/) just out, please try it out.
