### ISSUE TITLE
How to Change gRPC server IP in REST API Server docker?

### ISSUE THREAD

**Issue by gunpal5** [vectorch-ai/ScaleLLM#30]
I am trying to run the ScaleLLM on windows PC. docker on windows doesn't support --net=host flag. I am trying to setup the network between the docker containers. how can I change or the default IP (127:0:0:1:8888) in REST API server?

**Comment by guocuimi** [comment]
Hello you can config ports with following gflags .

'--grpc-server=***'
'''
grpcServerEndpoint = flag.String("grpc-server", "127.0.0.1:8888", "gRPC server endpoint")
	httpServerEndpoint = flag.String("http-server", "0.0.0.0:8080", "HTTP server endpoint")
'''
