### ISSUE TITLE
使用yi-34b时模型不会主动提停止生成，会不停地生成低质量的重复的内容，应该如何调整？

### ISSUE THREAD

**Issue by BUJIDAOVS** [vectorch-ai/ScaleLLM#31]
![51b4075bed878f03dcfdb6291b4db6c](https://github.com/vectorch-ai/ScaleLLM/assets/98118374/79f89eab-04ec-4865-946c-190202400c29)

**Comment by guocuimi** [comment]
seems you forget to add gflag for Yi model. `--model_type=Yi`
please double check
1> pull latest docker image
2> add '--model_type=Yi' for Yi models.

**Comment by BUJIDAOVS** [comment]
Thank you so much. It works perfectly now.

发件人：Michael Mi ***@***.***>
发送日期：2023-12-14 14:42:18
收件人：vectorch-ai/ScaleLLM ***@***.***>
抄送人：BUJIDAOVS ***@***.***>,Author ***@***.***>
主题：Re: [vectorch-ai/ScaleLLM] 使用yi-34b时模型不会主动提停止生成，会不停地生成低质量的重复的内容，应该如何调整？ (Issue #31)

seems you forget to add gflag for Yi model. --model_type=Yi
 please double check
 1> pull latest docker image
 2> add '--model_type=Yi' for Yi models.

**Comment by BUJIDAOVS** [comment]
Thank you so much. It works perfectly now!
And here is a part of my docker-compose :
command: --logtostderr --model_path=/models/Yi-34B-Chat-4bits --model_id=Yi-34B-Chat-4bits --model_type=Yi
