### ISSUE TITLE
grpc server connection error

### ISSUE THREAD

**Issue by qiezikuangge** [vectorch-ai/ScaleLLM#32]
I deploy Yi Model use the follow command
```
docker run -it --gpus=all --net=host --shm-size=1g \
  -v $HOME/.cache/huggingface/hub:/models \
  -e HF_MODEL_ID=01-ai/Yi-34B-Chat-8bits \
  -e DEVICE=auto \
  docker.io/vectorchai/scalellm:latest --logtostderr --model_type=Yi
```
And then, I try use restful API use this command
```
docker run -it --net=host \
  docker.io/vectorchai/scalellm-gateway:latest --logtostderr
```
But when I use requests command, I get grpc error the errMess is 
```
connection error: desc="transport: Error while dialing: dial tcp 127.0.0.1:8888: connect: connection refused"
```
I test curl localhost:9999/health is ok

**Comment by guocuimi** [comment]
Did you see any errors?

**Comment by qiezikuangge** [comment]
Nothing, I start these two docker, it's successed and the last line was "start xxx server at/on 0.0.0.0:8080/8888/9999". And I try request it, but don't see anything in command window.

**Comment by guocuimi** [comment]
Weird. Could you try restart your gateway docker instance?

**Comment by qiezikuangge** [comment]
I solved the problem by using the follow command
```
docker run -it --net=host \
  docker.io/vectorchai/scalellm-gateway:latest --logtostderr -grpc-server xxxx:8888
```

**Comment by qiezikuangge** [comment]
But I meet a new issue, it seems like openai version or pydantic error?
I test a RestAPI by using python requests, but get error
```
{"error":{"code":3,"message":"proto": (line 1:148): unknown field \"stop\""}}
```

**Comment by guocuimi** [comment]
good to know that you fixed the connection issue. 
yeah. the `stop` is not supported yet for now but in our plan. 
are you using stop field in your request?
https://platform.openai.com/docs/api-reference/chat/create#chat-create-stop

**Comment by qiezikuangge** [comment]
> good to know that you fixed the connection issue. yeah. the `stop` is not supported yet for now but in our plan. are you using stop field in your request? https://platform.openai.com/docs/api-reference/chat/create#chat-create-stop

Thanks for your quickly reply and this issue is solved. But I meet a new question about cuda..... The error log is:
```
terminate called after throwing an instance of 'c10::Error'
terminate called recursively
    what(): CUDA error: no kernel image is avaliable for execution on the device
```
And also has other log but it's in our production env, sorry I can't provide this

**Comment by guocuimi** [comment]
It appears that the GPU in your production cluster is not of a newer architecture than Turing.
please note that, for now, ScaleLLM only supports GPUs that newer than Turing architecture. We do have plans to extend support to older architectures such as sm70 and sm75. Our team is actively engaged in the process of rewriting attention and quantization kernels to facilitate this expansion. Thank you for your understanding and patience as we work towards enhancing compatibility.

**Comment by qiezikuangge** [comment]
Ok, thanks for your work. Hope the project be better and better. And I would close the issue
