### ISSUE TITLE
Will the result callback called in a threadsafe/coruntine safe way? #322

### ISSUE THREAD

**Issue by tp-nan** [vectorch-ai/ScaleLLM#323]
Hi, I'm a little worried about the following callback, which might be called in C++ from another thread(s), and writing to asyncio.Queue
https://github.com/vectorch-ai/ScaleLLM/blob/ea0f6bf5d747a2cc6c6419501430c27545e1408c/scalellm/llm_engine.py#L180

**Comment by guocuimi** [comment]
Thanks to GIL, it is safe to call python callback from c++ in a async way. 
you can find more details from pybind11 tests:
 https://github.com/pybind/pybind11/blob/master/tests/test_callbacks.cpp#L222

**Comment by tp-nan** [comment]
> https://github.com/pybind/pybind11/blob/master/tests/test_callbacks.cpp#L222

The test invlove a `res.push_back` where res is type of List. In our case, res is type of asyncio.Queue, so `asyncio.run_coroutine_threadsafe` might be needed

**Comment by guocuimi** [comment]
Could you elaborate the reason behind your suggestion? I am not sure if I get the point. Thanks

**Comment by guocuimi** [comment]
Thank you! Let me dig more about this potential issue. Good catch!

**Comment by guocuimi** [comment]
After further investigation, I believe you are correct. `asyncio.Queue` is not thread-safe, so we'll need to use run_coroutine_threadsafe or call_soon_threadsafe to schedule tasks into the event loop from a separate thread. I'm currently working on implementing the fix.

Good catch! Thank you!

**Comment by tp-nan** [comment]
looking forward to it
