### ISSUE TITLE
The output from the API lacks "usage" content, which is causing compatibility issues when trying to use the API with other tools.

### ISSUE THREAD

**Issue by BUJIDAOVS** [vectorch-ai/ScaleLLM#34]
The output from the API lacks "usage" content, which is causing compatibility issues when trying to use the API with other tools.

（with Yi model）

**Comment by guocuimi** [comment]
Thanks for reporting this issue. We will add this support in next release next week.

**Comment by guocuimi** [comment]
just a quick update: added usage in response in diff https://github.com/vectorch-ai/ScaleLLM/commit/298f246d8f304eef414e47ff55ae46200af257b9. the change would be available in next release.
