### ISSUE TITLE
 Driver Version: 535.54.03    CUDA Version: 12.2 ，运行报错“OpenAI API returned an error 503: {"error":{"code":14,"message":"connection error: desc = \"transport: Error while dialing: dial tcp: lookup scalellm on 127.0.0.11:53: server misbehaving\""}}”

### ISSUE THREAD

**Issue by Missliuff** [vectorch-ai/ScaleLLM#37]
我的驱动版本是535.54.03，cuda版本是12.2，运行后出现报错“OpenAI API returned an error 503: {"error":{"code":14,"message":"connection error: desc = \"transport: Error while dialing: dial tcp: lookup scalellm on 127.0.0.11:53: server misbehaving\""}}”
请问出现此报错的原因是什么？谢谢~

**Comment by guocuimi** [comment]
Did you see any error messages from the grpc server?

**Comment by Missliuff** [comment]
> Did you see any error messages from the grpc server?

<img width="731" alt="微信图片_20231222151134" src="https://github.com/vectorch-ai/ScaleLLM/assets/26702797/42a463a4-90e0-4f56-9b01-ef7b3afeef7a">
是红框这个吗？

**Comment by guocuimi** [comment]
you should check 'scalellm' service. sounds core dump generated. could you share the call stacks?
