### ISSUE TITLE
Support for Visual Models (i.e. LLaVA)

### ISSUE THREAD

**Issue by omarmhaimdat** [vectorch-ai/ScaleLLM#75]
It would be great if you could introduce support for visual instruction models such as [LLaVA](https://github.com/haotian-liu/LLaVA)

**Comment by guocuimi** [comment]
Thank you for expressing interest in ScaleLLM! We're excited about expanding our support to include multi-Modal like LLaVA. It's on our roadmap, and we'll prioritize integrating LLaVA once we've completed our current milestones. Stay tuned for updates!

**Comment by omarmhaimdat** [comment]
Thank you for the quick response, can you please share the roadmap?

**Comment by guocuimi** [comment]
sure. please check it out. [ScaleLLM Roadmap](https://github.com/vectorch-ai/ScaleLLM/issues/84)

**Comment by omarmhaimdat** [comment]
Thank you !
